#mkp_router/src/mkp_clusterization/Dockerfile.clusterization

FROM psilas85/mkprouter-base:latest

WORKDIR /app

# Copia TODO o src
COPY ./src /app/src
COPY ./requirements.txt /app/requirements.txt

ENV PYTHONPATH=/app/src

RUN pip install --no-cache-dir -r /app/requirements.txt

EXPOSE 8004

CMD ["uvicorn", "mkp_clusterization.api.cluster_api:app", "--host", "0.0.0.0", "--port", "8004"]

